version: '2'

volumes:
  wiki-data:
    external: true

services:
  wiki:
    image: ratijas/moinmoin
    build: .
    command: -t Europe/Moscow
    env_file:
      - wiki.env
    volumes:
      - "wiki-data:/usr/local/share/moin/data"
      - "/etc/hosts:/etc/hosts:ro"

  nginx:
    image: nginx
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
    links:
      - wiki
    depends_on:
      - wiki
    volumes:
      - "./ssl/cert.pem:/etc/ssl/certs/cert.pem:ro"
      - "./ssl/privkey.pem:/etc/ssl/private/key.pem:ro"
      - "./wiki.nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./img/favicon.ico:/etc/nginx/html/favicon.ico:ro"

